apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: "git@gitlab.com:shahaf4/gitops-app.git"
    targetRevision: HEAD
    path: apps/main-app

  destination:
    server: "https://kubernetes.default.svc"
    namespace: app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
