{
 "title": "main-app",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(flask_http_request_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rate of HTTP GET requests over the last 5 minutes:",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 12, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(flask_http_request_total{method=\"GET\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{method=\"GET\", status=\"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(flask_http_request_total{method=\"GET\", status=\"404\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of HTTP requests by method and status code:",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (method, status) (flask_http_request_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}